### ISSUE TITLE
Filter buttons don't loose focus after being unclicked

### ISSUE THREAD

**Issue by nschwertner** [smart-classic/smart_sample_apps#19]
Reproduction steps (provided by Rachel Eastwood):
1. Enter Long-Term View (any patient)
2. Click "Leg" in Arm/Leg filter to select it
   - Result is as expected: Leg button changes from gray (the "unselected"
     state) to blue upon clicking, then white upon releasing (the "selected"
     state)
3. Click "Leg" again
   - Result is NOT as expected: Leg button changes from white to blue upon
     clicking, but stays blue (the "clicking" state) upon releasing rather than
     returning to gray (the "unselected" state). IMAGE ATTACHED
4. Workaround: To get button back to gray, click an inactive area of the
   screen

Analysis:

The issue manifests itself under Firefox and IE9, but not under Chrome and Safari. It seems like a bug in jQuery UI is responsible:

http://stackoverflow.com/questions/3861307/jqueryui-button-remains-pressed-after-opening-ui-dialog-with-it-in-firefox
http://bugs.jqueryui.com/ticket/5604

Upgrading to the latest jQuery (1.7.2) and jQueryUI (1.8.22) does not resolve the issue. The stackoverflow page describe possible solutions, but they all have issues.

Will have to revisit.

**Comment by jmandel** [comment]
jQuery haven't merged a patch yet, but did we try the suggestion from the ticket?

**Comment by reastwood** [comment]
This issue seems to also be true of the circular timeline sliders - they stay blue (plus have dotted white line around them) until I click an inactive area.

Not a big problem for the video, just reporting it.

**Comment by nschwertner** [comment]
I did experiment with a few fixes and found the one applied above to work without the need to hack the jQuery UI code. Let's hope that jQueryUI will fix this bug in their next release. For now, this should do it.

**Comment by nschwertner** [comment]
While this fix works while staying within the browser window, the blue accent on the clicked button returns when tabbing to another window and then coming back to the browser. This seems to be an acceptable compromise for not having to maintain our own branch of jQuery UI.
