### ISSUE TITLE
1% difference between percentile in calculator and short term view

### ISSUE THREAD

**Issue by nschwertner** [smart-classic/smart_sample_apps#20]
## Rachel E's report

Allen Vitalis's Short Term, Long Term, and Table Views show 69%/66% for 16 July 2012, but the Calculator shows 68%/66%. This is very close--69 vs. 68--but the raw data values are exactly the same in both places (6y 11m, 124 cm, male, 104/63 mmHg) so it seems odd.
## Analysis

The percentile calculated in the short term, long term, and table views is based on the true age down to the second. In contrast, the percentile calculated via the calculator is rounded down to the month as result of the UI design. Occasionally this rounding will result in a 1% difference in a percentile calculation when the data for a BP reading is copied into the calculator.
## Resolution

The percentiles computed in the calculator are correct based on the UI (years + months). Changing the underlying calculation method to anything else will be misleading. The calculation in the st/lt/table views is a bit more precise than it needs to be, so we can make it round the age to the month to match the calculator mechanics.

**Comment by jmandel** [comment]
I think that using the full birthdate (i.e. to the day) is the right thing to do in our calculations.  Changing the app's core logic to match the ad-hoc calculator seems like a funny compromise.  I agree a 1% difference can seem "odd," but rounding the real data to close the gap seems worse to me.

**Comment by nschwertner** [comment]
No problem. It's easy enough to undo this change, if that's desirable.
