### ISSUE TITLE
The SMART REST apps need a mechanism for configuring the app secret token

### ISSUE THREAD

**Issue by nschwertner** [smart-classic/smart_sample_apps#21]

**Comment by jmandel** [comment]
You mean our sample apps?  E.g. in a config file would be nice; and providing (at least for RxReminder) a per-server config would be good, like:

``` python
consumer_secrets_by_server = {
  "http://localhost:7000/" : "my-local-consumer-secret",
  "http://smarti2b2.org/" : "my-i2b2-consumer-secret",
}
```

**Comment by p2** [comment]
You also need to store the secret there, don't you?

**Comment by jmandel** [comment]
Yes, I meant to write secret, duh :-)  (I'm assuming a fixed consumer key as defined in the app's manifest.)

Example updated above.

**Comment by p2** [comment]
Ah I see, makes sense. :)

Related to that, I've seen that other implementations issue a scrambled key additionally to the scrambled secret for apps. Indivo and SMART issue deductible keys anybody knows or can guess; not sure if this adds much security, just wanted to add that because the scheme you propose would require to use the same key across all sites.

**Comment by jmandel** [comment]
Giving the apps a fixed identifier seems like a good opportunity for us to
inject a little bit of sanity into the app installation / oauth
provisioning process (which is otherwise, at this point, basically
out-of-band).  At any rate there's not a security risk to using a fixed
username (OAuth consumer key) and secret password (OAuth consumer secret).

Are there specific implementation concerns?

**Comment by p2** [comment]
No, no concerns from my side, having a fixed and actually readable identifier sounds great. Ignore my comment, this just sprang to my mind and I thought to share.

**Comment by nschwertner** [comment]
What I had in mind was making the consumer secret for the sample REST apps part of their configuration settings (settings.py). Regardless of whether the app provides the key to the server via the manifest or the server generates the key and somebody has to copy it manually into the app, the process will be much easier when the key is in the config settings.

When I reloaded the manifests of the REST apps on our dev sandbox (as result of setting up a dev api-verifier hosted app), I found out that unless the manifest provides an explicit consumer secret, the load script generates a random secret and the app are broken unless somebody manually copies the secret over to them. As a stop-gap measure until I get a chance to revisit the Admin UI, I added code to the load script to print the generated key in the console and also modded the load script on the dev sandbox to always generate the good old "smart-secret" consumer key.

Now, my concern with having the apps set the consumer secret via the manifest is that for apps which are hosted in the cloud and shared across multiple containers, the manifest makes the consumer secret publicly visible (i.e. not much of a secret any more). From the above discussion though, I am not under the impression that this may not be the case. 

The idea of having the app use a different key depending on the server that it connect to is an interesting one. I can see where this may come handy for the hosted apps.

**Comment by jmandel** [comment]
1.  Take a look at the way Indivo handles this:  indivo has a _separate_
   file that sits next to the manifest and contains the consumer secret.  This
   is a probably better separation of concerns than storing everything in the
   main settings file.
2.  Nobody is suggesting storing the app's consumer secret in the the app's
   public manifest.  This manifest should, as you say, live in the cloud and
   be sharable across installs.

**Comment by nschwertner** [comment]
Storing the secret in a separate file on the app end - I like it. We cannot mandate this as part of the standard, it is an app developer's choice as to whether to do it this way or some other way. However, we can do it for our sample apps to help manage the secret.

It is this piece of code:
https://github.com/chb/smart_server/blob/dev/load_tools/load_one_app.py#L36
which made me think that we are moving in the direction of setting the secret via the app manifest. But perhaps this is not what you had in mind at all? For publicly hosted apps where the manifest is exposed to the public, we certainly don't want to have the secret in it. For non-hosted apps, it's ok to have the secret in the manifest, I guess.

**Comment by jmandel** [comment]
Never intended to suggest storing secrets in the app manifest.  Manifests
are for public consumption.

The code you referenced loads some parameters, including a consumer secret,
from the command-line or a calling function (_not_ from the manifest).

What I was suggesting (and pointing to Indivo for) is managing a set of
files on the container side that sit alongside app manifests and include
any secret or install-specific data (such as the consumer secret).  So, for
example, it's easy to recreate state after a server reset.

**Comment by nschwertner** [comment]
Ahh, I see. Ok, never mind...

Now, about retaining the secrets state on the container side, I already have a script for loading all the hosted rest apps and the external apps on the sandboxes. A quick way to manage the consumer secrets would be to simply add the consumer secrets in these scripts, since the app loader can take them as params and manage them this way. However, having a set of install-specific app config files and a script that iterates over them to load the apps would be nice.
