### ISSUE TITLE
Django 1.6.5 support

### ISSUE THREAD

**Issue by dattachandan** [smart-classic/smart_sample_apps#59]
When i run 
D:\Downloads\src\python\smart_sample_apps>python manage.py runconcurrentserver 0.0.0.0:800
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager

D:\Downloads\src\python\smart_sample_apps>python -V
Python 2.7.6

D:\Downloads\src\python\smart_sample_apps>python
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import django
> > > print(django.get_version())
> > > 1.6.5

http://docs.smartplatforms.org/framework/reference-implementation/install-ubuntu.html
It says, Django 1.3+ is fine, but i guess i can't use 1.6.5. Only upto 1.4.

**Comment by nschwertner** [comment]
Thank you for letting us known. Yes, indeed, only Django 1.3 is supported currently. I've added a note to this in the documentation source:
https://github.com/chb/smart_docs_2/commit/5ff283c38f2198e71505868184beeae33e851090
