### ISSUE TITLE
URL parameters are not decoded

### ISSUE THREAD

**Issue by michelemottini** [smart-classic/smart_sample_apps#60]
Trying to launch the app using a URL with encoded parameters:

```
https://fhir.smartplatforms.org/apps/growth-chart/launch.html?iss=https%3A%2F%2Fcareev13%3A8080%2FFHIR
```

fails, it is necessary to use non encoded parameters:

```
https://fhir.smartplatforms.org/apps/growth-chart/launch.html?iss=https://careev13:8080/FHIR
```

(Is this the right repo though? It is linked [here](http://smartplatforms.org/smart-app-gallery/pediatric-growth-chart/) but the source code does not seem to match)

**Comment by jmandel** [comment]
Thanks for the report! An encoded issuers URL should absolutely be supported (and is correct).  

 (FYI the repo is at https://github.com/smart-on-fhir/apps but we haven't had GH issues enabled.) 

We'll also update the apps in our gallery (the link you shaded above)  to point to the SMART on FHIR versions, but currently the gallery is actually demonstrating the "SMART Classic" version of the app.

**Comment by nschwertner** [comment]
Fixed the URL encoding issue (https://github.com/smart-on-fhir/client-js/commit/14fe67468f85aa069ffbac841b41995b652103e4) and pushed into our public sandbox

**Comment by michelemottini** [comment]
...the fix fixes `iss`, but what about the other URL parameters (`launch`, `state` etc)? I think they should be all url-decoded. Maybe it would be better to modify the `urlParam()` function?

(Sorry to be a pest)

**Comment by nschwertner** [comment]
The JS client does not really care about the contents of the `launch`,  `state`, etc parameters. These get passed through to the authorization server and the API server. So, I am not sure that it would make sense to do any processing on them.

**Comment by jmandel** [comment]
Thanks for your careful attention -- not pestering in the least!

The parameters that should be passed into thin page are: 'iss'  and
'launch'. I think it makes sense for both to be url encoded. (I don't think
"state" is passed to the app's launch endpoint.)

On Wed, Jan 14, 2015, 12:44 nschwertner notifications@github.com wrote:

 The JS client does not really

about the contents of the launch, state, etc parameters. These get passed
through to the authorization server and the API server. So, I am not sure
that it would make sense to do any processing on them.

## 

Reply to this email directly or view it on GitHub
https://github.com/smart-platforms/smart_sample_apps/issues/60#issuecomment-69957990.<img
src="

https://that

ci3.googleusercontent.com/proxy/WrhiKg-bC2dNXCJSOyz6XRVgrWBy5oJ3vrIvRV45TnDKWu4Yj1zWrzE50z_YrviMU2MvL6SAZrxA6LDHLMzffMoJSs-d6SmijD06UPMcqowYX9pR7E1FPZVOw3wSp-zB5INndMjOe1adn5exg72XmcTVS0i6-Q=s0-d-e1-ft#https://github.com/notifications/beacon/AATHAQPON5jHieekCp5ddLS9JBVVBvojks5nhqJ6gaJpZM4DR5sq.gif
">

**Comment by nschwertner** [comment]
FHIR Starter is now URL encoding the `iss` and `fhirServiceUrl` parameters:
https://github.com/smart-on-fhir/apps/commit/be743025db64e875b3bea9d8b532aa92fd7ee893

The remaining parameters should be URL encoded and the apps should pass them unchanged between the API and authentication servers. We will work this into the documentation. Thank you for bringing it to our attention.

**Comment by nschwertner** [comment]
Encode all parameters, just in case:
https://github.com/smart-on-fhir/apps/commit/3ce00ed3349444ea6d6b50d8c419a7e754d8056f

**Comment by michelemottini** [comment]
> The JS client does not really care about the contents of the launch, state,
> etc parameters. These get passed through to the authorization server and
> the API server. So, I am not sure that it would make sense to do any
> processing on them.
> 
> The authorization code that is received as a URL parameter is then POSTed
> to get back the token - and I am pretty sure that it is URL-encoded in the
> POSTed data, so if it is not URL-decoded when it is received it is going to
> be messed up if it contains non-alphanumeric characters

**Comment by jmandel** [comment]
Thanks for following up on this.

I think we're discussing a couple of related issues here at the same time
(the 'launch'  request vs. the actual OAuth2 dance that happens after the
launch request).

Let's write out an example of a complete flow, labeling the steps and
parameters, so we can be more precise. I'll take a pass at this when I'm at
a proper keyboard (tomorrow) unless someone beats me to it :-)

**Comment by nschwertner** [comment]
Well, I am not the competitive type that would want to steal the show, so will let you do this. ;)

For what it's worth, here is a dump of the call parameters from a sample run through an app launch and authorization in out reference stack:

```
Launch
  launchURI:
      iss: {uri}
      launch: {string}

Authorization sequence
   authorizeURI:
      response_type: "code"
      redirect_uri: {uri}
      scope: "launch:{string} patient/*.read ..."
      state: {string}
      client_id: {string}
   redirectURI:
      code: {string}
      state: {string}
   tokenURI:
      code: {string}
      grant_type: "authorization_code"
      redirect_uri: {redirectURI}
      client_id: {string}
```

**Comment by jmandel** [comment]
Thanks Nikolai! So in short, there are two key sequences:
1. Launch
2. Authorize

In each sequence, various data are passed as URL parameters . In all cases, these parameters should be url-encoded. Sometimes it will make no difference (e.g. `encodeURIComponent("123") == "123"`) but in general this is the correct procedure. When one party generates a value that's designated as opaque to the other party, what does this imply? For example during the Launch sequence above, the EHR generates a `launch` value that's opaque to the app. Imagine the server generates a value of `some&opaque|value`. This should be passed to the app as `?launch=some%26opaque%7Cvalue`. Then, the app decodes this to obtain the actual value, which it then encodes again in order to pass it along during the Authorization step. (Nikolai points out that, since this value is opaque to the app, decoding it and then encoding it again shouldn't make any difference - which  is true. But treating all parameters "the same" -- which is to say, properly -- will simplify our code and make it easier to follow.

Any time anyone wants to read the value of a url parameter, it should be decoded first. Any time anyone wants to send a url parameter, it should be encoded first.

Any concerns with this edict?

**Comment by michelemottini** [comment]
> Any time anyone wants to read the value of a url parameter, it should be
> decoded first. Any time anyone wants to send a url parameter, it should be
> encoded first.

I think this would be the safest choice

**Comment by michelemottini** [comment]
(....are you going to the Connectathon in Cleveland ? )

**Comment by nschwertner** [comment]
I am going to the connectathon in San Antonio this weekend (http://wiki.hl7.org/index.php?title=FHIR_Connectathon_8). Didn't know there would be one in Cleveland...

**Comment by michelemottini** [comment]
I am going at the IHE Connectathon: http://www.ihe.net/Connectathon/ - a
couple of the profiles being tested there are FHIR-based

...I did not know that there were FHIR Connectathons....with better winter
locations...

**Comment by nschwertner** [comment]
Tweaked the JS client to decode all incoming parameters and then encode them in all GET calls.
https://github.com/smart-on-fhir/client-js/commit/372237bf5dfdda6d4b22c90ad4efea1177d62cbf
